name: Deploy

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup
              uses: ./.github/actions/setup

            - name: Build
              run: pnpm run build

    # deploy:
    #     name: Production
    #     runs-on: ubuntu-latest
    #     needs: [build]
    #     environment: production

    #     steps:
    #         - name: Configure SSH
    #           run: |
    #               mkdir -p ~/.ssh/
    #               printf "%s\n" "${{ secrets.SSH_KEY }}" > ~/.ssh/deployment.key
    #               chmod 600 ~/.ssh/deployment.key
    #               cat >>~/.ssh/config <<END
    #               Host deployment
    #                 HostName ${{ secrets.SSH_HOST }}
    #                 User ${{ secrets.SSH_USER }}
    #                 IdentityFile ~/.ssh/deployment.key
    #                 StrictHostKeyChecking no
    #               END

    #         - name: Update production
    #           run: ssh deployment 'cd ~/Website && ./update.sh'
