name: Test Farming Weight

on:
  push:
    branches: [main]
    paths:
      - 'packages/farming-weight/**'
  pull_request:
    paths:
      - 'packages/farming-weight/**'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
 
      - name: Change to farming-weight directory
        run: cd packages/farming-weight

      - name: Run tests
        run: pnpm test